# Pandas

In [1]:
# download data from stack overflow annual developer survey

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data.txt')

In [4]:
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3998,3999,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,Splunk,ChatGPT;GitHub Copilot;Microsoft Copilot,NaN,When I don’t trust AI’s answers;When I want to...,Integration of buisness requirements in code. ...,63808.0,5.0
3999,4000,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,20.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All of them,179823.0,10.0
4000,4001,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,5.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemi...,"perplexity, phind",When I don’t trust AI’s answers;When I want to...,Debugging,15047.0,8.0
4001,4002,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,12.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,69609.0,9.0
4002,4003,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",18.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I’m stuck...,NaN,106190.0,6.0

In [5]:
df.shape

(4003, 172)

In [6]:
df.head() # displays 5 top rows

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [7]:
df.tail(2)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
4001,4002,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,12.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,69609.0,9.0
4002,4003,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",18.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I’m stuck...,NaN,106190.0,6.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4003 entries, 0 to 4002
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 5.3+ MB

###### Data frame is like dictionary of lists from python
Series are rows of single column

In [9]:
people = {
    "first":["Jai", "Tom", "Ram"],
    "last":["Sharma", "Thomas", "Verma"],
    "email":["sharmaji@gmail.com", "tony@gmail.com", "ramgopal@gmail.com"]
}

In [10]:
print(people["first"])

['Jai', 'Tom', 'Ram']

In [11]:
df1 = pd.DataFrame(people)

In [12]:
df1

  first    last               email
0   Jai  Sharma  sharmaji@gmail.com
1   Tom  Thomas      tony@gmail.com
2   Ram   Verma  ramgopal@gmail.com

In [13]:
type(df1["email"]) #Series are rows of single column

pandas.core.series.Series

In [14]:
df1["email"]  # Python way

0    sharmaji@gmail.com
1        tony@gmail.com
2    ramgopal@gmail.com
Name: email, dtype: object

In [15]:
df1.email  # DataFrame way

0    sharmaji@gmail.com
1        tony@gmail.com
2    ramgopal@gmail.com
Name: email, dtype: object

In [16]:
df1[["last", "email"]]  # change columns sequence

     last               email
0  Sharma  sharmaji@gmail.com
1  Thomas      tony@gmail.com
2   Verma  ramgopal@gmail.com

In [17]:
 # columns
df1.columns

Index(['first', 'last', 'email'], dtype='object')

In [18]:
df1.iloc[0]

first                   Jai
last                 Sharma
email    sharmaji@gmail.com
Name: 0, dtype: object

In [19]:
df1.iloc[1]

first               Tom
last             Thomas
email    tony@gmail.com
Name: 1, dtype: object

In [20]:
df1

  first    last               email
0   Jai  Sharma  sharmaji@gmail.com
1   Tom  Thomas      tony@gmail.com
2   Ram   Verma  ramgopal@gmail.com

In [21]:
df1.iloc[2]

first                   Ram
last                  Verma
email    ramgopal@gmail.com
Name: 2, dtype: object

In [22]:
df1.iloc[1,1] # second item second row

'Thomas'

In [23]:
df1

  first    last               email
0   Jai  Sharma  sharmaji@gmail.com
1   Tom  Thomas      tony@gmail.com
2   Ram   Verma  ramgopal@gmail.com

In [24]:
df1.iloc[[0, 1],2]  # first and second rows third column

0    sharmaji@gmail.com
1        tony@gmail.com
Name: email, dtype: object

In [25]:
df1.iloc[[0,1],1]  # first and second rows second column

0    Sharma
1    Thomas
Name: last, dtype: object

In [26]:
df1.iloc[[1,2], 0]

1    Tom
2    Ram
Name: first, dtype: object

In [27]:
df1.iloc[[0,2]]  # Only first and third rows

  first    last               email
0   Jai  Sharma  sharmaji@gmail.com
2   Ram   Verma  ramgopal@gmail.com

In [28]:
# loc allows by searching using label or column name
df1.loc[[0,2], ["last", "first"]]  # first and third rows and indexed by key

     last first
0  Sharma   Jai
2   Verma   Ram

In [29]:
df.head

<bound method NDFrame.head of       ResponseId                      MainBranch              Age  \
0              1  I am a developer by profession  25-34 years old
1              2  I am a developer by profession  25-34 years old
2              3  I am a developer by profession  35-44 years old
3              4  I am a developer by profession  35-44 years old
4              5  I am a developer by profession  35-44 years old
...          ...                             ...              ...
3998        3999  I am a developer by profession  25-34 years old
3999        4000  I am a developer by profession  35-44 years old
4000        4001  I am a developer by profession  25-34 years old
4001        4002  I am a developer by profession  25-34 years old
4002        4003  I am a developer by profession  35-44 years old

                                              EdLevel  \
0     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
1                 Associate degree (A.A., A.S., etc.)
2        Bachelor’s degree (B.A., B.S., B.Eng., etc.)
3        Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
...                                               ...
3998  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3999  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
4000     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4001  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
4002     Bachelor’s degree (B.A., B.S., B.Eng., etc.)

                                             Employment  \
0                                              Employed
1                                              Employed
2     Independent contractor, freelancer, or self-em...
3                                              Employed
4     Independent contractor, freelancer, or self-em...
...                                                 ...
3998                                           Employed
3999                                           Employed
4000  Independent contractor, freelancer, or self-em...
4001                                           Employed
4002                                           Employed

                                         EmploymentAddl  WorkExp  \
0       Caring for dependents (children, elderly, etc.)      8.0
1                                                   NaN      2.0
2                                     None of the above     10.0
3                                     None of the above      4.0
4       Caring for dependents (children, elderly, etc.)     21.0
...                                                 ...      ...
3998                                  None of the above      2.0
3999                                  None of the above     20.0
4000                                  None of the above      5.0
4001                                  None of the above     12.0
4002  Caring for dependents (children, elderly, etc....     18.0

                                        LearnCodeChoose  \
0     Yes, I am not new to coding but am learning ne...
1     Yes, I am not new to coding but am learning ne...
2     Yes, I am not new to coding but am learning ne...
3     Yes, I am not new to coding but am learning ne...
4     No, I am not new to coding and did not learn n...
...                                                 ...
3998  Yes, I am not new to coding but am learning ne...
3999  Yes, I am not new to coding but am learning ne...
4000  Yes, I am not new to coding but am learning ne...
4001  Yes, I am not new to coding but am learning ne...
4002  Yes, I am not new to coding but am learning ne...

                                              LearnCode  \
0     Online Courses or Certification (includes all ...
1     Online Courses or Certification (includes all ...
2     Online Courses or Certification (includes all ...
3     Other online resources (e.g. standard search, ...
4                                                   NaN
...                                                 ...
3998  Online Courses or Certification (includes all ...
3999  Other online resources (e.g. standard search, ...
4000  Other online resources (e.g. standard search, ...
4001  Other online resources (e.g. standard search, ...
4002  Other online resources (e.g. standard search, ...

                                            LearnCodeAI  ...  \
0     Yes, I learned how to use AI-enabled tools for...  ...
1     Yes, I learned how to use AI-enabled tools for...  ...
2     Yes, I learned how to use AI-enabled tools for...  ...
3     Yes, I learned how to use AI-enabled tools for...  ...
4     Yes, I learned how to use AI-enabled tools for...  ...
...                                                 ...  ...
3998  Yes, I learned how to use AI-enabled tools for...  ...
3999  Yes, I learned how to use AI-enabled tools for...  ...
4000  Yes, I learned how to use AI-enabled tools for...  ...
4001  No, I learned something that was not related t...  ...
4002  Yes, I learned how to use AI-enabled tools for...  ...

     AIAgentOrchestration  AIAgentOrchWrite AIAgentObserveSecure  \
0               Vertex AI               NaN                  NaN
1                     NaN               NaN                  NaN
2                     NaN               NaN                  NaN
3                     NaN               NaN                  NaN
4                     NaN               NaN                  NaN
...                   ...               ...                  ...
3998                  NaN               NaN                  NaN
3999                  NaN               NaN                  NaN
4000                  NaN               NaN                  NaN
4001                  NaN               NaN                  NaN
4002                  NaN               NaN                  NaN

     AIAgentObsWrite                                    AIAgentExternal  \
0                NaN                                            ChatGPT
1                NaN                                                NaN
2                NaN   ChatGPT;Claude Code;GitHub Copilot;Google Gemini
3                NaN                                ChatGPT;Claude Code
4                NaN                                                NaN
...              ...                                                ...
3998          Splunk           ChatGPT;GitHub Copilot;Microsoft Copilot
3999             NaN                                                NaN
4000             NaN  ChatGPT;Claude Code;GitHub Copilot;Google Gemi...
4001             NaN                                                NaN
4002             NaN                                                NaN

        AIAgentExtWrite                                            AIHuman  \
0                   NaN                    When I don’t trust AI’s answers
1                   NaN  When I don’t trust AI’s answers;When I want to...
2                   NaN  When I don’t trust AI’s answers;When I want to...
3                   NaN  When I don’t trust AI’s answers;When I want to...
4                   NaN                    When I don’t trust AI’s answers
...                 ...                                                ...
3998                NaN  When I don’t trust AI’s answers;When I want to...
3999                NaN  When I don’t trust AI’s answers;When I want to...
4000  perplexity, phind  When I don’t trust AI’s answers;When I want to...
4001                NaN  When I don’t trust AI’s answers;When I want to...
4002                NaN  When I don’t trust AI’s answers;When I’m stuck...

                                                 AIOpen  ConvertedCompYearly  \
0                 Troubleshooting, profiling, debugging              61256.0
1                             All skills. AI is a flop.             104413.0
2     Understand how things actually work, problem s...              53061.0
3                                                   NaN              36197.0
4     critical thinking, the skill to define the tas...              60000.0
...                                                 ...                  ...
3998  Integration of buisness requirements in code. ...              63808.0
3999                                        All of them             179823.0
4000                                          Debugging              15047.0
4001                                                NaN              69609.0
4002                                                NaN             106190.0

      JobSat
0       10.0
1        9.0
2        8.0
3        6.0
4        7.0
...      ...
3998     5.0
3999    10.0
4000     8.0
4001     9.0
4002     6.0

[4003 rows x 172 columns]>

In [30]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [31]:
df["Employment"].head()

0                                             Employed
1                                             Employed
2    Independent contractor, freelancer, or self-em...
3                                             Employed
4    Independent contractor, freelancer, or self-em...
Name: Employment, dtype: object

In [32]:
df.loc[0]

ResponseId                                                           1
MainBranch                              I am a developer by profession
Age                                                    25-34 years old
EdLevel                Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
Employment                                                    Employed
                                            ...
AIAgentExtWrite                                                    NaN
AIHuman                                When I don’t trust AI’s answers
AIOpen                           Troubleshooting, profiling, debugging
ConvertedCompYearly                                            61256.0
JobSat                                                            10.0
Name: 0, Length: 172, dtype: object

In [33]:
df.loc[0:2, "Employment"]

0                                             Employed
1                                             Employed
2    Independent contractor, freelancer, or self-em...
Name: Employment, dtype: object

In [34]:
df1

  first    last               email
0   Jai  Sharma  sharmaji@gmail.com
1   Tom  Thomas      tony@gmail.com
2   Ram   Verma  ramgopal@gmail.com

In [35]:
df1.reset_index(inplace=True)

In [36]:
df1

   index first    last               email
0      0   Jai  Sharma  sharmaji@gmail.com
1      1   Tom  Thomas      tony@gmail.com
2      2   Ram   Verma  ramgopal@gmail.com

In [37]:
df1.reset_index(inplace=False)

   level_0  index first    last               email
0        0      0   Jai  Sharma  sharmaji@gmail.com
1        1      1   Tom  Thomas      tony@gmail.com
2        2      2   Ram   Verma  ramgopal@gmail.com

In [38]:
df1

   index first    last               email
0      0   Jai  Sharma  sharmaji@gmail.com
1      1   Tom  Thomas      tony@gmail.com
2      2   Ram   Verma  ramgopal@gmail.com

In [39]:
df1.reset_index(drop=True)

   index first    last               email
0      0   Jai  Sharma  sharmaji@gmail.com
1      1   Tom  Thomas      tony@gmail.com
2      2   Ram   Verma  ramgopal@gmail.com

In [40]:
df1

   index first    last               email
0      0   Jai  Sharma  sharmaji@gmail.com
1      1   Tom  Thomas      tony@gmail.com
2      2   Ram   Verma  ramgopal@gmail.com

In [41]:
df1.drop(columns='index', inplace=True)

In [42]:
df1

  first    last               email
0   Jai  Sharma  sharmaji@gmail.com
1   Tom  Thomas      tony@gmail.com
2   Ram   Verma  ramgopal@gmail.com

In [43]:
schema_df1 = df1.columns

In [44]:
schema_df1

Index(['first', 'last', 'email'], dtype='object')

In [45]:
schema_df1.tolist()

['first', 'last', 'email']

In [46]:
df1.sort_index(ascending=False)

  first    last               email
2   Ram   Verma  ramgopal@gmail.com
1   Tom  Thomas      tony@gmail.com
0   Jai  Sharma  sharmaji@gmail.com

In [47]:
df1

  first    last               email
0   Jai  Sharma  sharmaji@gmail.com
1   Tom  Thomas      tony@gmail.com
2   Ram   Verma  ramgopal@gmail.com

In [50]:
filt = df1['last'] != 'Sharma'

In [51]:
filt

0    False
1     True
2     True
Name: last, dtype: bool

In [52]:
df1[filt]

  first    last               email
1   Tom  Thomas      tony@gmail.com
2   Ram   Verma  ramgopal@gmail.com